version: "1.0"

visor:
  taps:

orb:
  backends:
    pktvisor:
      binary: "/usr/local/sbin/pktvisord"
      config_file: "/etc/orb/agent.yaml"

    cloudprober:
      binary: "/usr/local/sbin/cloudprober"
      config_file: "/etc/cloudprober/cloudprober.cfg"
      
